### ISSUE TITLE
Failure to save log prevents emails from being sent

### ISSUE THREAD

**Issue by agronick** [treyhunner/django-email-log#14]
I'm having intermittent database issues and wondering why I didn't get any emails about it. When the Email.objects.create method fails it never gets to send the email. The create method should be wrapped in a try block.

**Comment by spapas** [comment]
Hello @agronick , this is a very late reply but my understanding is the issue you mention is definitely possible but if my database wasn't working, sending the email would be the smallest of my problems :|

Also I don't even know if eating the exception as you propose would be the correct behavior here. Maybe it's better to let it propagate so you will get an error and be able to fix it. 

@treyhunner do you have an opinion on this?

**Comment by treyhunner** [comment]
I agree that the database not existing seems like it would often be a bigger problem than email not working.

I could also imagine a scenario where the database (or at least the one that the email logs are stored in) isn't a big part of a Django project, say on an app that uses Mongo DB for most of its data and doesn't touch the ORM much except for admin tasks.

This seems like it might be a good place to use logging. Maybe a try-except with an error/critical log message that logs the exception, noting it happened while attempting to log an email.

**Comment by agronick** [comment]
This is a 5 year old comment. I do not have any involvement with this package anymore since I have changed companies.

The problem is not that arbitrary emails are not being sent. The problem is that one of Django's built in and default features is emailing error reports. If the error report involves the database, it will never be sent.

**Comment by spapas** [comment]
@agronick that's a really good point! Thank you! This will definitely be fixed.
