### ISSUE TITLE
Great library...can it detect bouncebacks?

### ISSUE THREAD

**Issue by kyledavelaar** [treyhunner/django-email-log#16]
Hi Trey,

Great job here.  I'm in need of logging bouncebacks.  I'm guessing we can't do this here but just want to confirm and see if you know a way to do this without using something like Sendgrid.

Thanks, Kyle

**Comment by treyhunner** [comment]
That'd depend on your email provider. I don't know how to do that with Sendgrid. I assume it's possible though.
