### ISSUE TITLE
Status of this package

### ISSUE THREAD

**Issue by spapas** [treyhunner/django-email-log#26]
Hello @treyhunner can you please confirm if this package is still maintained?  I'm using it in a number of projects and this package makes it difficult for me to update t o django 4.x. I have created a fork and use this in my requirements but I prefer having proper reqs. 

Thank you

**Comment by treyhunner** [comment]
@spapas I don't use this app in any of my own projects right now. I should probably consider moving this to [jazzband](https://jazzband.co/) eventually, so others can help support it more easily.

**Comment by spapas** [comment]
Hello @treyhunner yes it would be great if you could move the project to jazzband! 

I use this package all the time because we send transactional emails and it's important to be able to take a look at some past emails to see what the users actually got. Also it's really useful for uat to keep track of the emails that got sent while business users were testing... 

Thank you for your great work!

Kind regards,
Serafeim

**Comment by treyhunner** [comment]
@spapas I just released 1.1.0 on PyPI with Django 4.0 support.

I'm glad you get value from this project! Until Would you have any interest in helping maintain it (keep the Django version current with passing tests mostly)? I'll also look into moving it to Jazzband, but even then it'll need usual maintainers.

**Comment by spapas** [comment]
Yes of course, I'll be happy to keep the django version current since I need it for my projects :)
