### ISSUE TITLE
Invalid IP Hosts Error

### ISSUE THREAD

**Issue by tracesense** [treyhunner/django-email-log#34]
Hi in production any idea how to stop the email_log_email table being clogged up with 'INVALID HTTP HOST HEADER' errors? Thanks

**Comment by spapas** [comment]
Hello @tracesense this is not really related with the django-email-log package. Django will receive a requests with the wrong host and will throw. You need to configure your web server to *not* send these requests to your django app.

**Comment by tracesense** [comment]
Thanks mate
