### ISSUE TITLE
Tests are failing for python 3.6 on ubuntu latest

### ISSUE THREAD

**Issue by spapas** [treyhunner/django-email-log#37]
It seems that the ubuntu-latest image on github actions will now use ubuntu 22 instead of 20. This results in not supporting python 3.6 anymore, see here:

https://github.com/actions/runner-images/issues/6399

There are two solutions I can think of:

* Drop support for python 3.6 or
* Change ubuntu-latest (https://github.com/treyhunner/django-email-log/blob/main/.github/workflows/tests.yml#L9) to 20.04

I think that since python 3.6 is already EOL https://devguide.python.org/versions/ we can safely drop support for it.

@treyhunner any thoughts ?

**Comment by treyhunner** [comment]
I agree. 👍 Let's drop support for anything that's been EOL'd for over a year.
